	ORG	0x8000
	EXX
	PUSH	HL
	CALL	KECCAKF
	POP	HL
	EXX
	RET
	INCLUDE	"keccak.asm"
	INCLUDE	"keccaktab.asm"
KECCAKB:EQU	IOTAT+0x100
KECCAKS:EQU	KECCAKB+48
KECCAKQ:EQU	KECCAKS+200
KECCAKO:EQU	KECCAKQ+8
KECCAKW:EQU	KECCAKO+1
